### ISSUE TITLE
stdlib 9 support

### ISSUE THREAD

**Issue by jcpunk** [theforeman/puppet-puppetserver_foreman#28]
With the release of puppetlabs-stdlib 9 there have been some deprecations.

```
Evaluation Error: Error while evaluating a Function Call, deprecation. ensure_packages. This function is deprecated, please use stdlib::ensure_packages instead.
```

**Comment by evgeni** [comment]
https://github.com/theforeman/puppet-puppetserver_foreman/commit/aa0724f2483c3e46cd073feacc9cb13ac269ae89 is merged and CI ensures that we work on stdlib 9
